### PR TITLE
Merge performance improvements into master

### LINKED ISSUE #14: Performance tests have low code quality and are unfair
The performance tests within this respository are pretty unfair because there hasn't been looked at JIT optimalizations and the timing of the actions differs per implementation.

I will be working within a fork to fix these issues. Just wanted to make this issue to spread light on the issue and ask if this project is still active under your development.

### PR DESCRIPTION
**Pull request by bartdebever**
PerformanceTest:
- Rewritten benchmarks to be more fair towards EF6
- Added JIT warmup
- Added option to specifiy the amount of runs
- Improved formatting on logging
- Disabled method optimalization

General:
- Updated package version to Entity Framework 6.2.0 (Note that I could not run the tests using SqlServerCE)
- Updated framework to 4.6.1 (Unsure if this makes sense, have not worked on a NuGet package before)

Fixes #14

### CODE REVIEW

**Comment by bartdebever** [comment]
Sample output
```
Specify the amount of runs that should be done, must be greater than 0.
The 'runs' indicate how many times an action is performed on the entity count.
1
Performing Warm-Up
Standard iteration with 25 entities
[EFU] Insert entities 25 iterations took 44 ms
[EFU] Update all entities with 'a' 25 iterations took 7 ms
[EFU] Bulk update all with a random read 25 iterations took 36 ms
[EFU] Delete all entities with 'a' 25 iterations took 2 ms
[EFU] Delete all entities 25 iterations took 2 ms

[EF6] Insert entities 25 iterations took 22 ms
[EF6] Update all entities with 'a' 25 iterations took 8 ms
[EF6] Update all with 'a' random read 25 iterations took 9 ms
[EF6] Delete all entities with 'a' 25 iterations took 1 ms
[EF6] Delete all entities 25 iterations took 7 ms

Standard iteration with 100 entities
[EFU] Insert entities 100 iterations took 46 ms
[EFU] Update all entities with 'a' 100 iterations took 8 ms
[EFU] Bulk update all with a random read 100 iterations took 9 ms
[EFU] Delete all entities with 'a' 100 iterations took 3 ms
[EFU] Delete all entities 100 iterations took 3 ms

[EF6] Insert entities 100 iterations took 77 ms
[EF6] Update all entities with 'a' 100 iterations took 3 ms
[EF6] Update all with 'a' random read 100 iterations took 19 ms
[EF6] Delete all entities with 'a' 100 iterations took 1 ms
[EF6] Delete all entities 100 iterations took 16 ms

Standard iteration with 250 entities
[EFU] Insert entities 250 iterations took 44 ms
[EFU] Update all entities with 'a' 250 iterations took 9 ms
[EFU] Bulk update all with a random read 250 iterations took 10 ms
[EFU] Delete all entities with 'a' 250 iterations took 4 ms
[EFU] Delete all entities 250 iterations took 5 ms

[EF6] Insert entities 250 iterations took 63 ms
[EF6] Update all entities with 'a' 250 iterations took 5 ms
[EF6] Update all with 'a' random read 250 iterations took 47 ms
[EF6] Delete all entities with 'a' 250 iterations took 2 ms
[EF6] Delete all entities 250 iterations took 51 ms

Standard iteration with 500 entities
[EFU] Insert entities 500 iterations took 70 ms
[EFU] Update all entities with 'a' 500 iterations took 10 ms
[EFU] Bulk update all with a random read 500 iterations took 11 ms
[EFU] Delete all entities with 'a' 500 iterations took 4 ms
[EFU] Delete all entities 500 iterations took 7 ms

[EF6] Insert entities 500 iterations took 166 ms
[EF6] Update all entities with 'a' 500 iterations took 7 ms
[EF6] Update all with 'a' random read 500 iterations took 97 ms
[EF6] Delete all entities with 'a' 500 iterations took 3 ms
[EF6] Delete all entities 500 iterations took 69 ms

Standard iteration with 1000 entities
[EFU] Insert entities 1000 iterations took 60 ms
[EFU] Update all entities with 'a' 1000 iterations took 11 ms
[EFU] Bulk update all with a random read 1000 iterations took 15 ms
[EFU] Delete all entities with 'a' 1000 iterations took 4 ms
[EFU] Delete all entities 1000 iterations took 13 ms

[EF6] Insert entities 1000 iterations took 291 ms
[EF6] Update all entities with 'a' 1000 iterations took 9 ms
[EF6] Update all with 'a' random read 1000 iterations took 199 ms
[EF6] Delete all entities with 'a' 1000 iterations took 7 ms
[EF6] Delete all entities 1000 iterations took 148 ms

Standard iteration with 2500 entities
[EFU] Insert entities 2500 iterations took 71 ms
[EFU] Update all entities with 'a' 2500 iterations took 17 ms
[EFU] Bulk update all with a random read 2500 iterations took 19 ms
[EFU] Delete all entities with 'a' 2500 iterations took 5 ms
[EFU] Delete all entities 2500 iterations took 28 ms

[EF6] Insert entities 2500 iterations took 802 ms
[EF6] Update all entities with 'a' 2500 iterations took 28 ms
[EF6] Update all with 'a' random read 2500 iterations took 490 ms
[EF6] Delete all entities with 'a' 2500 iterations took 14 ms
[EF6] Delete all entities 2500 iterations took 454 ms

Standard iteration with 5000 entities
[EFU] Insert entities 5000 iterations took 157 ms
[EFU] Update all entities with 'a' 5000 iterations took 26 ms
[EFU] Bulk update all with a random read 5000 iterations took 31 ms
[EFU] Delete all entities with 'a' 5000 iterations took 8 ms
[EFU] Delete all entities 5000 iterations took 61 ms

[EF6] Insert entities 5000 iterations took 1491 ms
[EF6] Update all entities with 'a' 5000 iterations took 44 ms
[EF6] Update all with 'a' random read 5000 iterations took 974 ms
[EF6] Delete all entities with 'a' 5000 iterations took 73 ms
[EF6] Delete all entities 5000 iterations took 840 ms

Standard iteration with 25000 entities
[EFU] Insert entities 25000 iterations took 624 ms
[EFU] Update all entities with 'a' 25000 iterations took 107 ms
[EFU] Bulk update all with a random read 25000 iterations took 100 ms
[EFU] Delete all entities with 'a' 25000 iterations took 17 ms
[EFU] Delete all entities 25000 iterations took 194 ms

[EF6] Insert entities 25000 iterations took 7338 ms
[EF6] Update all entities with 'a' 25000 iterations took 196 ms
[EF6] Update all with 'a' random read 25000 iterations took 5168 ms
[EF6] Delete all entities with 'a' 25000 iterations took 175 ms
[EF6] Delete all entities 25000 iterations took 3690 ms

Standard iteration with 50000 entities
[EFU] Insert entities 50000 iterations took 1207 ms
[EFU] Update all entities with 'a' 50000 iterations took 185 ms
[EFU] Bulk update all with a random read 50000 iterations took 184 ms
[EFU] Delete all entities with 'a' 50000 iterations took 26 ms
[EFU] Delete all entities 50000 iterations took 376 ms

[EF6] Insert entities 50000 iterations took 15652 ms
[EF6] Update all entities with 'a' 50000 iterations took 400 ms
[EF6] Update all with 'a' random read 50000 iterations took 10077 ms
[EF6] Delete all entities with 'a' 50000 iterations took 331 ms
[EF6] Delete all entities 50000 iterations took 8229 ms

Standard iteration with 10000 entities
[EFU] Insert entities 10000 iterations took 175 ms
[EFU] Update all entities with 'a' 10000 iterations took 47 ms
[EFU] Bulk update all with a random read 10000 iterations took 76 ms
[EFU] Delete all entities with 'a' 10000 iterations took 17 ms
[EFU] Delete all entities 10000 iterations took 395 ms

[EF6] Insert entities 10000 iterations took 2918 ms
[EF6] Update all entities with 'a' 10000 iterations took 68 ms
[EF6] Update all with 'a' random read 10000 iterations took 1940 ms
[EF6] Delete all entities with 'a' 10000 iterations took 85 ms
[EF6] Delete all entities 10000 iterations took 1709 ms

Standard iteration with 100000 entities
[EFU] Insert entities 100000 iterations took 1811 ms
[EFU] Update all entities with 'a' 100000 iterations took 365 ms
[EFU] Bulk update all with a random read 100000 iterations took 436 ms
[EFU] Delete all entities with 'a' 100000 iterations took 43 ms
[EFU] Delete all entities 100000 iterations took 592 ms

[EF6] Insert entities 100000 iterations took 29152 ms
[EF6] Update all entities with 'a' 100000 iterations took 738 ms
[EF6] Update all with 'a' random read 100000 iterations took 19764 ms
[EF6] Delete all entities with 'a' 100000 iterations took 625 ms
[EF6] Delete all entities 100000 iterations took 15191 ms

Completed benchmarks
```

**Comment by RudeySH** [comment]
> Updated framework to 4.6.1 (Unsure if this makes sense, have not worked on a NuGet package before)

Do your changes need 4.6.1? If not, I'd rather not bother the users of the NuGet package with the requirement of targeting 4.6.1. In that case please revert back to 4.0.

If the use of 4.6.1 is justified, you need to run `Update-Package -Reinstall` in the package manager console, to [re-target NuGet packages](https://stackoverflow.com/a/40681448/1185136).

**Comment by RudeySH** [comment]
Actually, the same goes for bumping EF from 6.1.3 to 6.2. I'm not sure if I want to do that. This would force all users of the NuGet package to upgrade to 6.2.

While the differences between 6.1.3 and 6.2 are minimal, I have personally run into an issue with 6.2 before, see https://github.com/aspnet/EntityFramework6/issues/398 (it's closed but isn't fixed)

**Comment by bartdebever** [comment]
Didn't think about this and forgot about the EF 6.2 issues (seen you on the MiniProfiler issues as well)

Again, first time working on NuGet packages so just went a bit auto mode. Will downgrade again when I'm able to.

**Comment by bartdebever** [comment]
>Reverted both .net Framework and EF upgrades but am unable to test if the project is still working due
to it giving me errors

I'm an idiot, nevermind. All works and is good on .net Framework 4 and EF 6.1.3!

**Comment by RudeySH** [comment]
I had to undo a lot of small changes your pull request was introducing, see https://github.com/RudeySH/EntityFramework.Utilities/pull/15/commits/ec6cff605d056254d9ddf79d2d58cd1148c20503. Please review these changes, you should try to avoid committing stuff like this in future pull requests. Especially paths that refer to your local file system. 😄

**Comment by bartdebever** [comment]
Lots of these changes that are in the config etc are issues to begin with.

I looked through the commit history and most of the stuff is just EF being EF and Visual Studio being Visual Studio.

Should have I not have committed these? Maybe yes it's a valid point.

**Pull request merged**
